# 上传文件总的最大值
spring:
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  redis:
    host: 47.104.185.237
    password: 17185383573
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.104.185.237:3306/skydrive
server:
  port: 8080
mybatis:
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    top:
      liuyanhua:
        skydrive:
          mapper: debug
